// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentRestAPI.Models;

#nullable disable

namespace StudentRestAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentRestAPI.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(1942, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "Kwase@gmail.com",
                            FirstName = "Akash",
                            Gender = 0,
                            LastName = "Gupa",
                            PhotoPath = "images/Akaash.png"
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(1994, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "Mia@gmail.com",
                            FirstName = "Mia",
                            Gender = 1,
                            LastName = "Gupa",
                            PhotoPath = "images/Akaash.png"
                        },
                        new
                        {
                            StudentId = 3,
                            DateOfBirth = new DateTime(1992, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "Kua@gmail.com",
                            FirstName = "Kua",
                            Gender = 0,
                            LastName = "Gupa",
                            PhotoPath = "images/Akaash.png"
                        },
                        new
                        {
                            StudentId = 4,
                            DateOfBirth = new DateTime(1955, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 4,
                            Email = "Ama@gmail.com",
                            FirstName = "Ama",
                            Gender = 1,
                            LastName = "Gupa",
                            PhotoPath = "images/Akaash.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
